models:
  kimi_k2:
    id: "kimi-k2-instruct"

  gpt_oss_120b:
    id: "gpt-oss-120b"

  gpt_oss_20b:
    id: "gpt-oss-20b"

  qwen3_coder:
    id: "qwen3-coder-480b-a35b-instruct"

  qwen3_coder_30b:
    id: "qwen3-coder-30b-a3b-instruct"

  qwen3_235b_2507:
    id: "qwen3-235b-a22b-instruct-2507"

  qwen3_235b_2507_thinking:
    id: "qwen3-235b-a22b-thinking-2507"

  deepseek_r1_05_28:
    id: "deepseek-r1-0528"

  deepseek_v3_1:
    id: "deepseek-v3p1"

  deepseek_v3:
    id: "deepseek-v3"

  deepseek_r1:
    id: "deepseek-r1"

  glm_4p5:
    id: "glm-4p5"

  glm_4p5_air:
    id: "glm-4p5-air"

  llama_scout:
    id: "llama4-scout-instruct-basic"

  llama_maverick:
    id: "llama4-maverick-instruct-basic"

  llama_70b:
    id: "llama-v3p1-70b-instruct"

defaults:
  temperature: 0.1
  stream: true
  timeout: 70

base_url: https://api.fireworks.ai/inference/v1
web_app_model_library_url: https://app.fireworks.ai/api/models

rate_limiting:
  individual_ip_limit: 5
  ip_prefix_limit: 50
  redis_url: ${REDIS_URL:-redis://localhost:6379}
  daily_reset: true
  enabled: true
